# Generated by Django 3.2.5 on 2021-07-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0002_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
