# Generated by Django 3.2.5 on 2021-07-24 06:57

from django.db import migrations, models
import duties.utils


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0003_profile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=models.CharField(default=duties.utils.random_color, max_length=20),
        ),
    ]
