# Generated by Django 3.2.5 on 2021-07-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0005_auto_20210728_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
    ]
