# Generated by Django 3.2.5 on 2021-08-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('duties', '0006_auto_20210728_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groups_managed',
            field=models.ManyToManyField(related_name='managers', to='auth.Group'),
        ),
    ]
