name: CI

on: [push]

jobs:
  deploy:
#    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Pull from server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.KEY }}
          env:
            GIT_SSH_COMMAND: ${{ secrets.GIT_SSH_COMMAND }}
          script: cd ${{ secrets.PROJECT_PATH }} && git pull
#          script: cd ${{ secrets.PROJECT_PATH }} &&
