name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull
            ${{ secrets.POETRY_EXEC }} install
            ${{ secrets.POETRY_EXEC }} run python manage.py collectstatic --no-input
            sudo service duties.service restart
